<a href="https://colab.research.google.com/github/anunyathpn/PythonDataViz2026/blob/main/HW5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#HW5

เขียน function คูณ matrix

แล้ว test กับ matrix ขนาด

- (2,3)*(3,2)
- (4,4)*(4,1)
- (2,2)*(2,2)

In [1]:
import numpy as np

In [20]:
def multiple_mat(A, B):
    # เช็คว่าcolumnของA เท่ากับrowของBไหม
    if A.shape[1] != B.shape[0]:
        print("คูณไม่ได้ เนื่องจากขนาดไม่สอดคล้องกัน")
        return None

    # สร้างMatrixเปล่าสำหรับเก็บผลลัพธ์
    rows_A = A.shape[0]
    cols_B = B.shape[1]
    result = np.zeros((rows_A, cols_B), dtype=int)


    for i in range(rows_A):
        for j in range(cols_B):
            # เอาแถวที่ i ของ Aมาคูณกับหลักที่ j ของ B แล้วบวกหารวมกัน
            result[i][j] = np.sum(A[i, :] * B[:, j])

    return result

In [21]:

# 1. ทดสอบ Matrix (2,3) * (3,2)
m1 = np.array([[1, 2, 3],
               [4, 5, 6]])

m2 = np.array([[7, 8],
               [9, 10],
               [17, 12]])

print("--- Test (2,3) * (3,2) ---")
print(multiple_mat(m1, m2))
print()

# 2. ทดสอบ Matrix (4,4) * (4,1)
m3 = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12],
               [13, 14, 15, 16]])

m4 = np.array([[1],
               [2],
               [3],
               [4]])

print("--- Test (4,4) * (4,1) ---")
print(multiple_mat(m3, m4))
print()

# 3. ทดสอบ Matrix (2,2) * (2,2)
m5 = np.array([[1, 2],
               [3, 4]])

m6 = np.array([[5, 6],
               [7, 8]])

print("--- Test (2,2) * (2,2) ---")
print(multiple_mat(m5, m6))

--- Test (2,3) * (3,2) ---
[[ 76  64]
 [175 154]]

--- Test (4,4) * (4,1) ---
[[ 30]
 [ 70]
 [110]
 [150]]

--- Test (2,2) * (2,2) ---
[[19 22]
 [43 50]]
